global:
  postgresql:
    auth:
      postgresPassword: "Pay@1234AB!"

postgresqlDataDir: /var/lib/postgresql/data
architecture: replication
primary:
  name: primary
  persistence: 
    storageClass: allpay-postgresql-storage
    mountPath: /var/lib/postgresql
  resources:
    limits:
      memory: "10Gi"
      cpu: "10"
    requests:
      memory: "128Mi"
      cpu: "100m"

readReplicas:
  name: secondary
  replicaCount: 1
  persistence: 
    storageClass: allpay-postgresql-replica-storage
    mountPath: /var/lib/postgresql
  resources:
    limits:
      memory: "2Gi"
      cpu: "2"
    requests:
      memory: "128Mi"
      cpu: "100m"

replication:
  numSynchronousReplicas: 1