global:
  storageClass: allpay-postgresql-storage
  postgresql:
    auth:
      postgresPassword: "Pay@1234AB!"

architecture: replication
readReplicas:
  name: secondary
  replicaCount: 1

replication:
  numSynchronousReplicas: 1
