global:
  postgresql:
    auth:
      postgresPassword: "Pay@1234AB!"

postgresqlDataDir: /var/lib/postgresql/data
architecture: replication
primary:
  name: primary
  persistence: 
    storageClass: allpay-postgresql-storage
    mountPath: /var/lib/postgresql

readReplicas:
  name: secondary
  replicaCount: 1
  persistence: 
    storageClass: allpay-postgresql-replica-storage
    mountPath: /var/lib/postgresql

replication:
  numSynchronousReplicas: 1