version: '3.8'

services:
  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    ports:
      - "8082:8080" # Expose port 8080
    environment:
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/data # Directory where charts will be stored
      - DEBUG=true # Optional: Set to true for debugging logs
    volumes:
      - /data/charts:/data # Bind mount the local 'charts' directory
  ui:
     image: idobry/chartmuseumui:latest
     environment:
      CHART_MUSEUM_URL: "https://allpay-charts.scg.com/repositories"
      BASIC_AUTH_USERS: '[{"username":"admin", "password":"Pluto@2024"}]'
     ports:
      - 8084:8080
