services:
  registry:
    container_name: docker-registry
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /data/registry:/data
    networks:
      - docker-registry

  registry-ui:
    container_name: docker-registry-ui
    image: joxit/docker-registry-ui:latest
    restart: always
    ports:
      - 8080:5001
    environment:
      REGISTRY_TITLE: AllPay Registry
      REGISTRY_URL: http://docker-registry:5000
      REGISTRY_SSL: 'false'
    depends_on:
      - registry
    networks:
      - docker-registry

networks:
  docker_registry:
    name: docker-registry
    driver: bridge