{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jsreport.fullname" . }}-config
  namespace: {{ include "jsreport.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: jsreport
data:
  jsreport.config.json: |
    {{ .Values.configuration | toJson | indent 4 }}
