apiVersion: v1
kind: Secret
metadata:
  name: allpay-secret
  namespace: allpay
type: Opaque
data:
  DB_CONNECTION_ALLPAY_VENDOR: SG9zdD0xMC4xMDEuMy4xNTY7RGF0YWJhc2U9YWxscGF5X3ZlbmRvcjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1QYXlAMTIzNEFCITs=
  DB_CONNECTION_SHARE_MASTER: SG9zdD0xMC4xMDEuMy4xNTY7RGF0YWJhc2U9c2hhcmVfbWFzdGVyO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPVBheUAxMjM0QUIh
  DB_CONNECTION_VENDOR_PORTAL: SG9zdD0xMC4xMDEuMy4xNTY7RGF0YWJhc2U9dmVuZG9yX3BvcnRhbDtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1QYXlAMTIzNEFCIQ==
  DB_CONNECTION_MDS: U2VydmVyPTE3Mi4xOC4xMC44O0RhdGFiYXNlPU1EU19DQUQ7VXNlciBJZD1DQURfZGlzcGxheTtQYXNzd29yZD1VQUV6cyREISMyeGFRUl53O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZTs=
  DB_CONNECTION_DATA_WAREHOUSE: U2VydmVyPTE3Mi4zMC4xOTAuODM7RGF0YWJhc2U9U0FQTEFLRTtVc2VyIElkPUNBRF9WZW5kb3Jwb3J0YWw7UGFzc3dvcmQ9VmVuZG9yamFuMkAyNTtFbmNyeXB0PVRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlOw==
  MONGO_CONNECTION: bW9uZ29kYjovL3Jvb3Q6bWZsdiU1QjEyMzRAMTAuMTAxLjMuMTU2OjI3MDE3
  REDIS_CONNECTION: YWxscGF5LXJlZGlzLW1hc3Rlcjo2Mzc5LHBhc3N3b3JkPW1mbHZbMTIzNA==
  SAP_KEY_TOKEN: OTk1ODA0NTMtYTdkYS00ZTVmLTlhNTYtY2YxYjU2YmI1ZTA5
  DOA_KEY_TOKEN: MGQyZDk4NmEtNWViZS00NDRjLThkODUtY2U0YzZjYmY5ZGEy
  RABBITMQ_PASSWORD: bWZsdlsxMjM0
  ELATICSEARCH_API_KEY: T0VSclgxWndTVUpOVDBkM1IxbG5kRzFNTWxRNlluUkxZMDFaTm5CVGQxZFBTa05zZDBFNFkyZDBkdz09
  S3_ACCESS_KEY: QUtJQTRPVVZMTkw2WTJVTTNCM0s=
  S3_SECRET_KEY: bEZnVk1pbEEvRFc1QVBOUXRFam1Ea094QW9lSThVWkNGTngzMVB1Sg==
  OCR_API_KEY: c29tZVRva2Vu
  AI_API_KEY: c29tZVRva2Vu
  ALFRESCO_API_KEY: NTU5ZDE4ZjctN2MzNy00Mzc0LTg2ZmEtNWU4NTYwNDRjMTdi
  AFMS_USERNAME: U01GQVRLUw==
  AFMS_PASSWORD: dkBQNDB1Q3NjZw==
  INTERNAL_API_KEY_AP: cGlmaGRjMDQ3elFUQmN3V215QXB6RzU5WW00anIwVFA=
  INTERNAL_API_KEY_BG: TVIzSktrWXQ4YWNkemJXMW0xQTMzME9sQm9mY1hWNXo=
  INTERNAL_API_KEY_MQ: R1V0d1NNY1JIdkxRUzJXejB2WHljUllUTzlKRkNZUE4=
  INTERNAL_API_KEY_VP: RUtCUDNGTVBwUzJDODB5N2NjM0xRM3Zvd0x0eldDUFY=