global:
  defaultStorageClass: allpay-mongodb-storage

resources:
  limits:
    memory: "4Gi"
    cpu: "4"
    ephemeral-storage: "2Gi"
  requests:
    memory: "512Mi"
    cpu: "500m"
    ephemeral-storage: "50Mi"

auth:
  enabled: true
  rootUser: root
  rootPassword: mflv[1234
  usernames: ["admin", "admin"]
  passwords: ["mflv[1234", "mflv[1234"]
  databases: ["allPay", "vendorPortal"]

backup:
  enabled: true
  cronjob:
    schedule: "0 1 * * *"
    command:
    - /bin/bash
    - "-c"
    - |
      mongodump --username=${MONGODB_ROOT_USER} --password=${MONGODB_ROOT_PASSWORD} --authenticationDatabase=admin --host=${MONGODB_SERVICE_NAME} --port=${MONGODB_PORT_NUMBER} ${MONGODB_CLIENT_EXTRA_FLAGS} --db=allpay --gzip --archive=${MONGODUMP_DIR}/allpay-$(TZ="Asia/Bangkok" date '+%Y%m%d%H%M').gz &&
      mongodump --username=${MONGODB_ROOT_USER} --password=${MONGODB_ROOT_PASSWORD} --authenticationDatabase=admin --host=${MONGODB_SERVICE_NAME} --port=${MONGODB_PORT_NUMBER} ${MONGODB_CLIENT_EXTRA_FLAGS} --db=vendorPortal --gzip --archive=${MONGODUMP_DIR}/vendorPortal-$(TZ="Asia/Bangkok" date '+%Y%m%d%H%M').gz &&
      find ${MONGODUMP_DIR}/ -type f -name *.gz -mtime +30 -exec rm {} \;
    storage:
      storageClass: allpay-mongodb-backup-storage
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
        ephemeral-storage: "1Gi"
      requests:
        memory: "128Mi"
        cpu: "100m"
        ephemeral-storage: "50Mi"