apiVersion: v1
kind: PersistentVolume
metadata:
  name: allpay-mssql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "allpay-mssql-storage"
  nfs:
    path: /var/nfs/allpay-mssql
    server: 10.101.3.156
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: allpay-mssql-backup
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "allpay-mssql-backup-storage"
  nfs:
    path: /var/nfs/allpay-mssql-backup
    server: 10.101.3.156