replicas: 1

sa_password: "Pay@1234AB!"

service:
  type: ClusterIP
  port: 1433

pvc:
 storageClass: "allpay-mssql-storage"
 accessMode: ReadWriteOnce
 storage: 20Gi

backupPVC:
 storageClass: "allpay-mssql-backup-storage"
 accessMode: ReadWriteOnce
 storage: 100Gi