pipeline {
    agent any

    environment {
        TAG_NAME = ''
    }

    stages {
        stage('Checkout') {
            agent {
                label 'agent1'
            }
            steps {
                sh 'bash ~/prepare_pipeline.sh'
                script {
                    git branch: 'main',
                        credentialsId: 'jenkins_gitlab_ssh',
                        url: 'git@cad-gitlab.scg.com:allpay/vendor-portal-web.git'

                    TAG_NAME = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()

                    
                    // Checkout the latest tag
                    sh "git checkout ${TAG_NAME}"

                    stash includes: '**/*', name: 'project_source'
                }
            }
        }
        stage('Build') {
            agent {
                label 'agent1'
            }
            steps {
                unstash 'project_source'
                sh 'ls -al'
                sh """
                    echo '{ "version": "${TAG_NAME}" }' > ./src/app/version.json
                """
                sh "docker build -t allpay-registry.scg.com/vendor-portal-web:${TAG_NAME} --build-arg='BUILD_ENV=prd' -f Dockerfile ."
                sh "docker push allpay-registry.scg.com/vendor-portal-web:${TAG_NAME}"
                sh "helm package --app-version ${TAG_NAME} --version ${TAG_NAME} ./.charts"
                sh "helm cm-push vendor-portal-web-${TAG_NAME}.tgz allpay-charts -f --insecure"
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'echo Restarting deployment...'
                    withCredentials([sshUserPrivateKey(credentialsId: 'administrator_SCCBSAPVPR1_key', keyFileVariable: 'SSH_PRIVATE_KEY')]) {

                        sh """
                            ssh -i ${SSH_PRIVATE_KEY} -o StrictHostKeyChecking=no administrator@10.101.3.153 '
                            helm repo update allpay-charts
                            helm upgrade vendor-portal-web allpay-charts/vendor-portal-web --version ${TAG_NAME} -f ~/deployment/vendor-portal-web/values.prd.yaml -n allpay --insecure-skip-tls-verify'
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            emailext(
                subject: '$DEFAULT_SUBJECT',
                body: '$DEFAULT_CONTENT',
                to: '$DEFAULT_RECIPIENTS'
            )
        }
    }
}
