image:
  repository: allpay-registry.scg.com/allpay-web-prd
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.org/websocket-services: "allpay-web"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "100"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: allpay-vendor.scg.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: allpay-tls
    #   hosts:
    #     - allpay-vendor-qas.scg.com


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

replicaCount: 2