image:
  pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/connection-upgrade: "upgrade"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "allpay-session"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: allpay-vendor-dev.scg.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: allpay-tls
    #   hosts:
    #     - allpay-vendor-dev.scg.com