image:
  pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/connection-upgrade: "upgrade"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "allpay-session"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: allpay-vendor-api-dev.scg.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: allpay-tls
    #   hosts:
    #     - allpay-vendor-api-dev.scg.com

# Additional volumes on the output Deployment definition.
volumes:
- name: allpay-storage
  persistentVolumeClaim:
    claimName: allpay-dev-storage

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: allpay-storage
  mountPath: "/mnt/data"

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Dev
