apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allpay-dev-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "allpay-dev-storage"