apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allpay-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: "allpay-storage"