apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allpay-qas-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "allpay-qas-storage"