apiVersion: batch/v1
kind: CronJob
metadata:
  name: mssql-backup
spec:
  schedule: "0 2 * * *"  # Every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mssql-backup
            image: mcr.microsoft.com/mssql-tools
            command:
            - /bin/sh
            - -c
            - |
              date; echo Hello from the Kubernetes cluster
              # /opt/mssql-tools/bin/sqlcmd -S mssql-service -U sa -P "YourStrong!Passw0rd" -i /scripts/backup.sql
              # Ensure the backup file is copied or moved to a persistent storage or external location if needed
            volumeMounts:
              - mountPath: /scripts/backup.sql
                name: backup-scripts
                subPath: backup.sql
              - mountPath: /root/.ssh/id_rsa
                name: cronjob-default-config
                subPath: id_rsa
                readOnly: true
              - mountPath: /root/.ssh/config
                name: cronjob-default-config
                subPath: config
          restartPolicy: OnFailure
          volumes:
          - name: backup-scripts
            configMap:
              name: mssql-backup-scripts
