apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allpay-backup-mssql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: allpay-backup-mssql-storage
