apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allpay-mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: allpay-mssql-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allpay-mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: allpay-backup-mssql-storage
