services:
  agent1:
    container_name: agent1
    image: jenkins-agent1
    restart: always
    # ports:
    #   - 22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      dockerfile: ./Dockerfile.ssh_agent
      # args:
      #     HTTP_PROXY: http://CADAllpayVendor01:Avd%40%400113579@proxy-server.scg.com:3128/
      #     HTTPS_PROXY: http://CADAllpayVendor01:Avd%40%400113579@proxy-server.scg.com:3128/
    network_mode: "host"

networks:
  jenkins:
    driver: bridge

