# Use the official Ubuntu base image
FROM ubuntu:latest

# Set proxy variables
ARG HTTP_PROXY
ARG HTTPS_PROXY

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y \
    openjdk-17-jdk \
    openssh-server \
    git \
    curl \
    wget \
    unzip \
    apt-transport-https \
    ca-certificates \
    gnupg-agent \
    software-properties-common \
    nano

# Install Docker
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io

# Install Helm
RUN curl https://baltocdn.com/helm/signing.asc | apt-key add - && \
    apt-get install apt-transport-https --yes && \
    echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list && \
    apt-get update && \
    apt-get install -y helm

# RUN  helm plugin install https://github.com/chartmuseum/helm-push.git

# Set up SSH for Jenkins to communicate with the agent
RUN mkdir /var/run/sshd

# Create a Jenkins user
RUN useradd -m -s /bin/bash jenkins

# Set password for the Jenkins user (optional)
RUN echo "jenkins:1234AB" | chpasswd

RUN usermod -aG docker jenkins

RUN usermod -aG systemd-journal jenkins

COPY patch/patch_agent.sh /root

RUN chown root /root/patch_agent.sh
RUN chmod 744 /root/patch_agent.sh

RUN bash -c /root/patch_agent.sh

#RUN su - jenkins -c "helm plugin install https://github.com/chartmuseum/helm-push.git"
#RUN su - jenkins -c "helm repo add allpay-charts https://allpay-charts.scg.com/ --insecure-skip-tls-verify"

RUN sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config

# Standard SSH port
EXPOSE 2222

VOLUME /var/run/docker.sock:/var/run/docker.sock
# Start SSH daemon
CMD ["/usr/sbin/sshd", "-D"]