# Use the latest LTS (Long Term Support) version of Ubuntu
FROM ubuntu:latest

# Update package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk git curl && \
    apt-get clean;

# Set the JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

# Install Jenkins agent jar
RUN curl --create-dirs -sSLo /usr/share/jenkins/agent.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/4.7/remoting-4.7.jar && \
    chmod 755 /usr/share/jenkins && \
    chmod 644 /usr/share/jenkins/agent.jar

# Set up the Jenkins agent startup script
COPY jenkins-agent-startup.sh /usr/local/bin/jenkins-agent-startup.sh
RUN chmod +x /usr/local/bin/jenkins-agent-startup.sh

# Expose port for inbound agent connection
EXPOSE 50000

# Command to run the Jenkins agent
CMD ["/usr/local/bin/jenkins-agent-startup.sh"]
