image:
  pullPolicy: Always

# Additional volumes on the output Deployment definition.
volumes:
- name: allpay-storage
  persistentVolumeClaim:
    claimName: allpay-qas-storage

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: allpay-storage
  mountPath: "/mnt/data"

env:
- name: ASPNETCORE_ENVIRONMENT
  value: Qas
- name: Serilog__WriteTo__2__Args__apiKey
  valueFrom:
    secretKeyRef:
      name: allpay-secret
      key: ELASTICSEARCH_API_KEY
- name: ConnectionStrings__AllPay
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: DB_CONNECTION_ALLPAY_VENDOR
- name: ConnectionStrings__ShareMaster
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: DB_CONNECTION_SHARE_MASTER
- name: ConnectionStrings__VendorPortal
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: DB_CONNECTION_VENDOR_PORTAL
- name: ConnectionStrings__MdsCad
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: DB_CONNECTION_MDS
- name: ConnectionStrings__DataWarehouse
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: DB_CONNECTION_DATA_WAREHOUSE
- name: MongoDB__AllPay__ConnectionString
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: MONGO_CONNECTION
- name: MongoDB__VendorPortal__ConnectionString
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: MONGO_CONNECTION
- name: Redis__ConnectionString
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: REDIS_CONNECTION
- name: RabbitMQ__Password
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: RABBITMQ_PASSWORD
- name: SAPCheckClearing__SFTPUser
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: SAP_SFTP_USER
- name: SAPCheckClearing__SFTPPassword
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: SAP_SFTP_PASSWORD
- name: AFMS__Username
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: AFMS_USERNAME
- name: AFMS__Password
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: AFMS_PASSWORD
- name: OCR__APIKey
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: OCR_API_KEY
- name: AI__APIKey
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: AI_API_KEY
- name: Alfresco__APIKey
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: ALFRESCO_API_KEY
- name: Sap__KeyToken
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: SAP_KEY_TOKEN
- name: S3__AccessKey
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: S3_ACCESS_KEY
- name: S3__SecretKey
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: S3_SECRET_KEY
- name: InternalAPIKey
  valueFrom:
      secretKeyRef:
        name: allpay-secret
        key: INTERNAL_API_KEY_BG

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi