image:
  pullPolicy: Always

# Additional volumes on the output Deployment definition.
volumes:
- name: allpay-storage
  persistentVolumeClaim:
    claimName: allpay-storage

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: allpay-storage
  mountPath: "/mnt/data"

env:
- name: ASPNETCORE_ENVIRONMENT
  value: Production

nodeSelector:
  kubernetes.io/hostname: worker-02

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits: {}
